import type { TripContent } from '../types'

// Public content for the Peru trip (17–28 Oct 2026), from docs/peru/itinerario-peru.md.
// Times: flights are exact (local time); every other time is an approximate slot because the
// dossier gives none. Hotel names, phones and agency contacts are private (JSON import only).
// Bump seedVersion on every change so installed devices resync.

const content: TripContent = {
  tripId: 'peru-2026',
  seedVersion: 3,
  // Verify these numbers before travelling.
  emergency: {
    label: 'Emergencias en Perú',
    number: '105',
    description: 'Policía: 105 · Ambulancia (SAMU): 106 · Bomberos: 116.',
  },
  days: [
    {
      date: '2026-10-17',
      title: 'Madrid → Lima',
      cities: ['Madrid', 'Lima'],
      stay: {
        name: 'Hotel en Lima',
        meta: 'Miraflores · check-in desde 15:00',
        q: 'Miraflores, Lima',
      },
      legs: [
        {
          mode: 'plane',
          title: 'Vuelo Madrid → Lima',
          meta: 'Sale 13:20 · llega 18:20 (hora local)',
          q: 'Aeropuerto Internacional Jorge Chávez',
        },
        {
          mode: 'car',
          title: 'Traslado al hotel',
          meta: 'Incluido en el circuito',
          from: 'Aeropuerto Internacional Jorge Chávez',
          to: 'Miraflores, Lima',
        },
      ],
      plan: [
        {
          t: '13:20',
          title: 'Vuelo a Lima',
          place: 'Aeropuerto de Madrid-Barajas',
          q: 'Aeropuerto Adolfo Suárez Madrid-Barajas',
        },
        {
          t: '18:20',
          title: 'Llegada a Lima y traslado al hotel',
          place: 'Aeropuerto Jorge Chávez',
          q: 'Aeropuerto Internacional Jorge Chávez',
        },
      ],
      eat: [
        {
          when: 'Qué probar',
          name: 'Platos típicos de Lima',
          kind: 'Ceviche, tiradito, causa limeña, anticuchos, ají de gallina, picarones',
          tip: 'Ceviche: pescado curado en limón. Causa: papa amarilla rellena. Anticuchos: brochetas de corazón de res. Picarones: buñuelos de camote con miel.',
          q: 'cevicherías Lima',
        },
        {
          when: 'Cena libre',
          name: 'Panchita',
          kind: 'Criolla y parrilla · €€ · Miraflores',
          tip: 'Pide anticuchos y el plato criollo del día. Reserva recomendada; confirma el horario de cena porque llegas tarde.',
          q: 'Panchita Miraflores Lima',
        },
      ],
      see: [],
    },
    {
      date: '2026-10-18',
      title: 'Lima: Barranco, centro histórico y Museo Larco',
      cities: ['Lima'],
      stay: { name: 'Hotel en Lima', meta: 'Miraflores · segunda noche', q: 'Miraflores, Lima' },
      legs: [],
      plan: [
        {
          t: '09:00',
          title: 'Barranco y Puente de los Suspiros',
          place: 'Barranco',
          q: 'Puente de los Suspiros, Barranco, Lima',
        },
        {
          t: '11:00',
          title: 'Centro histórico: Plaza de Armas, Catedral y Casa Aliaga',
          place: 'Plaza de Armas de Lima',
          q: 'Plaza de Armas de Lima',
        },
        {
          t: '13:00',
          title: 'Clase express de pisco sour con mini causitas',
          place: 'Lima',
          q: 'Centro de Lima',
        },
        { t: '15:00', title: 'Museo Larco', place: 'Pueblo Libre', q: 'Museo Larco, Lima' },
        { t: '17:00', title: 'Tarde libre', place: 'Miraflores', q: 'Miraflores, Lima' },
      ],
      eat: [
        {
          when: 'Desayuno',
          name: 'Desayuno en el hotel',
          kind: 'Incluido',
          tip: 'Es la única comida incluida hoy.',
          q: 'Miraflores, Lima',
        },
        {
          when: 'Comida libre',
          name: 'Isolina Taberna Peruana',
          kind: 'Taberna criolla · €€–€€€ · Barranco',
          tip: 'Pide cau cau, lomo saltado o causa limeña (raciones grandes para compartir). En domingo cierra a las 19:00; conviene reservar.',
          q: 'Isolina Taberna Peruana Barranco Lima',
        },
        {
          when: 'Comida libre',
          name: 'Canta Rana',
          kind: 'Cevichería popular · €€ · Barranco',
          tip: 'Pide el ceviche con alcaparras y aguacate, o la parihuela. En domingo el horario puede ser reducido: confírmalo.',
          q: 'Canta Rana Barranco Lima',
        },
        {
          when: 'Cena',
          name: 'Cena libre en Miraflores',
          kind: 'Por tu cuenta',
          tip: 'Prueba el ceviche o la causa limeña.',
          q: 'restaurantes Miraflores Lima',
        },
        {
          when: 'Comida o cena libre',
          name: 'La Mar Cebichería',
          kind: 'Cevichería · €€€ · Miraflores',
          tip: 'Pide el ceviche clásico, el mixto o el tiradito. A mediodía suele haber cola: ve a las 12:00 o pasadas las 14:30. Confirma el horario de cena.',
          q: 'La Mar Cebichería Miraflores Lima',
        },
      ],
      see: [
        {
          name: 'Puente de los Suspiros',
          desc: 'Barrio bohemio de Barranco y arte urbano.',
          dur: 'Visita guiada',
          q: 'Puente de los Suspiros, Barranco, Lima',
        },
        {
          name: 'Plaza de Armas y Catedral',
          desc: 'La Catedral cierra los domingos por la mañana: confirmar el orden de la visita.',
          dur: 'Visita guiada',
          q: 'Catedral de Lima',
        },
        {
          name: 'Casa Aliaga',
          desc: 'Casona colonial en el centro histórico.',
          dur: 'Visita guiada',
          q: 'Casa Aliaga, Lima',
        },
        {
          name: 'Museo Larco',
          desc: 'Colección de arte precolombino.',
          dur: 'Visita guiada',
          q: 'Museo Larco, Lima',
        },
      ],
    },
    {
      date: '2026-10-19',
      title: 'Lima → Arequipa, la Ciudad Blanca',
      cities: ['Lima', 'Arequipa'],
      stay: {
        name: 'Hotel en Arequipa',
        meta: 'Centro histórico · check-in desde 15:00',
        q: 'Centro histórico de Arequipa',
      },
      legs: [
        {
          mode: 'plane',
          title: 'Vuelo Lima → Arequipa',
          meta: 'Sale 10:30 · llega 12:00',
          q: 'Aeropuerto Internacional Alfredo Rodríguez Ballón',
        },
        {
          mode: 'car',
          title: 'Traslado al hotel',
          meta: 'Llegada 12:00 · incluido en el circuito',
          from: 'Aeropuerto Internacional Alfredo Rodríguez Ballón',
          to: 'Centro histórico de Arequipa',
        },
      ],
      plan: [
        {
          t: '07:30',
          title: 'Traslado al aeropuerto',
          place: 'Aeropuerto Jorge Chávez',
          q: 'Aeropuerto Internacional Jorge Chávez',
        },
        {
          t: '10:30',
          title: 'Vuelo a Arequipa',
          place: 'Aeropuerto Jorge Chávez',
          q: 'Aeropuerto Internacional Jorge Chávez',
        },
        {
          t: '12:00',
          title: 'Llegada a Arequipa y traslado al hotel',
          place: 'Aeropuerto de Arequipa',
          q: 'Aeropuerto Internacional Alfredo Rodríguez Ballón',
        },
        {
          t: '15:00',
          title: 'Miradores de Carmen Alto y Yanahuara',
          place: 'Yanahuara',
          q: 'Mirador de Yanahuara, Arequipa',
        },
        {
          t: '16:30',
          title: 'Plaza de Armas de Arequipa',
          place: 'Centro histórico',
          q: 'Plaza de Armas de Arequipa',
        },
        {
          t: '17:30',
          title: 'Monasterio de Santa Catalina',
          place: 'Centro histórico',
          q: 'Monasterio de Santa Catalina, Arequipa',
        },
      ],
      eat: [
        {
          when: 'Desayuno',
          name: 'Desayuno en el hotel',
          kind: 'Incluido',
          tip: 'Sal con tiempo hacia el aeropuerto.',
          q: 'Miraflores, Lima',
        },
        {
          when: 'Qué probar',
          name: 'Platos típicos de Arequipa',
          kind: 'Rocoto relleno, chupe de camarones, ocopa, solterito, cuy chactado, queso helado',
          tip: 'Rocoto relleno: ají picante con carne y queso. Chupe: sopa espesa de camarones de río. Ocopa: papas con salsa de maní. Queso helado: postre de leche con canela.',
          q: 'picanterías Arequipa',
        },
        {
          when: 'Comida libre',
          name: 'La Nueva Palomino',
          kind: 'Picantería tradicional · €€ · Yanahuara',
          tip: 'Pide chupe de camarones, cuy frito o el almuerzo del día. Sin reservas: llega antes de las 12:00. Solo abre a mediodía.',
          q: 'La Nueva Palomino Picantería Arequipa',
        },
        {
          when: 'Comida libre',
          name: 'La Cau Cau II',
          kind: 'Picantería · €€ · Yanahuara',
          tip: 'Pide rocoto relleno, torrejitas o ají de calabaza. No acepta reservas y suele llenarse; las picanterías abren a mediodía.',
          q: 'La Cau Cau II Picantería Arequipa',
        },
        {
          when: 'Cena',
          name: 'Cena libre en Arequipa',
          kind: 'Por tu cuenta',
          tip: 'Plato típico de la zona: cuy chactado.',
          q: 'restaurantes centro histórico Arequipa',
        },
        {
          when: 'Cena libre',
          name: 'Chicha por Gastón Acurio',
          kind: 'Cocina arequipeña moderna · €€€ · Centro histórico',
          tip: 'Pide rocoto relleno, ocopa o locro de pecho. Reserva recomendada.',
          q: 'Chicha por Gastón Acurio Arequipa',
        },
        {
          when: 'Cena libre',
          name: 'Zig Zag Restaurant',
          kind: 'Carnes a la piedra volcánica · €€€ · Centro',
          tip: 'Pide la trilogía de carnes sobre piedra volcánica o el chupe de camarones. Reserva recomendada.',
          q: 'Zig Zag Restaurant Arequipa',
        },
      ],
      see: [
        {
          name: 'Mirador de Yanahuara',
          desc: 'Arcos de sillar con vistas al Misti.',
          dur: 'Visita guiada',
          q: 'Mirador de Yanahuara, Arequipa',
        },
        {
          name: 'Mirador de Carmen Alto',
          desc: 'Andenes y vistas de los volcanes.',
          dur: 'Visita guiada',
          q: 'Mirador de Carmen Alto, Arequipa',
        },
        {
          name: 'Plaza de Armas de Arequipa',
          desc: 'Plaza principal del centro histórico de la Ciudad Blanca.',
          dur: 'Visita guiada',
          q: 'Plaza de Armas de Arequipa',
        },
        {
          name: 'Monasterio de Santa Catalina',
          desc: 'Ciudadela colonial dentro de la ciudad.',
          dur: 'Visita guiada',
          q: 'Monasterio de Santa Catalina, Arequipa',
        },
      ],
    },
    {
      date: '2026-10-20',
      title: 'Arequipa → Cañón del Colca',
      cities: ['Arequipa', 'Patapampa', 'Chivay', 'Yanque'],
      stay: {
        name: 'Hotel en el valle del Colca',
        meta: 'Yanque · check-in desde 15:00',
        q: 'Yanque, Caylloma',
      },
      legs: [
        {
          mode: 'bus',
          title: 'Arequipa → Chivay',
          meta: 'Bus del circuito · carretera de alta montaña',
          from: 'Arequipa',
          to: 'Chivay',
        },
      ],
      plan: [
        { t: '08:00', title: 'Salida hacia el Colca', place: 'Arequipa', q: 'Arequipa' },
        {
          t: '09:30',
          title: 'Reserva Nacional de Salinas y Aguada Blanca',
          place: 'Pampa de Toccra',
          q: 'Reserva Nacional de Salinas y Aguada Blanca',
        },
        {
          t: '11:30',
          title: 'Mirador de Patapampa (4.910 m)',
          place: 'Patapampa',
          q: 'Mirador de los Volcanes Patapampa',
        },
        { t: '13:30', title: 'Llegada a Chivay y almuerzo', place: 'Chivay', q: 'Chivay' },
      ],
      eat: [
        {
          when: 'Desayuno',
          name: 'Desayuno en el hotel',
          kind: 'Incluido',
          tip: 'Sal temprano hacia el Colca.',
          q: 'Arequipa',
        },
        {
          when: 'Almuerzo',
          name: 'Almuerzo en Chivay',
          kind: 'Incluido',
          tip: 'Come ligero: estás por encima de 3.500 m.',
          q: 'Chivay',
        },
        {
          when: 'Qué probar',
          name: 'Platos típicos del Colca',
          kind: 'Alpaca, trucha, chupe de camarones, cuy, sopa de quinua, Colca Sour',
          tip: 'Según guías y reseñas; la carta varía. La alpaca es carne magra, a veces servida sobre piedra caliente. El Colca Sour lleva sancayo (fruto de cactus) en vez de limón.',
          q: 'restaurantes Chivay Colca',
        },
        {
          when: 'Cena libre',
          name: 'Sama Restaurante Café',
          kind: 'Cocina peruana · €€ · Chivay',
          tip: 'Pregunta por el plato regional o de alpaca del día. Está en Chivay: necesitarás taxi desde el alojamiento y confirmar que abre para cenar.',
          q: 'Sama Restaurante Café Chivay',
        },
        {
          when: 'Cena libre',
          name: 'Restaurante Maray',
          kind: 'Parrilla y cervecería · € · Chivay',
          tip: 'Pide el filete de alpaca servido sobre piedra volcánica (según reseñas). Pregunta el horario antes de ir.',
          q: 'Restaurante Maray Chivay',
        },
      ],
      see: [
        {
          name: 'Salinas y Aguada Blanca',
          desc: 'Alpacas y vistas del Misti, Pichu Pichu y Chachani.',
          dur: 'Parada en ruta',
          q: 'Reserva Nacional de Salinas y Aguada Blanca',
        },
        {
          name: 'Pampa de Toccra',
          desc: 'Parada junto a la reserva para admirar alpacas y volcanes.',
          dur: 'Parada en ruta',
          q: 'Pampa de Toccra, Arequipa',
        },
        {
          name: 'Mirador de Patapampa',
          desc: 'El punto más alto del viaje (4.910 m). Camina despacio.',
          dur: 'Parada en ruta',
          q: 'Mirador de los Volcanes Patapampa',
        },
      ],
    },
    {
      date: '2026-10-21',
      title: 'Cañón del Colca → Puno',
      cities: ['Cruz del Cóndor', 'Maca', 'Lagunillas', 'Puno'],
      stay: {
        name: 'Hotel en Puno',
        meta: 'Hotel pendiente de confirmar · check-in desde 15:00',
        q: 'Puno',
      },
      legs: [
        {
          mode: 'bus',
          title: 'Colca → Puno',
          meta: 'Bus del circuito · parada en Lagunillas',
          from: 'Chivay',
          to: 'Puno',
        },
      ],
      plan: [
        {
          t: '07:00',
          title: 'Cruz del Cóndor',
          place: 'Cañón del Colca',
          q: 'Mirador Cruz del Cóndor',
        },
        {
          t: '09:30',
          title: 'Pueblos de Pinchollo, Wayra Punku y Maca',
          place: 'Valle del Colca',
          q: 'Maca, Caylloma',
        },
        { t: '12:30', title: 'Almuerzo', place: 'Valle del Colca', q: 'Chivay' },
        {
          t: '15:00',
          title: 'Laguna de Lagunillas',
          place: 'Ruta a Puno',
          q: 'Laguna Lagunillas, Puno',
        },
        { t: '18:00', title: 'Llegada a Puno', place: 'Puno', q: 'Puno' },
      ],
      eat: [
        {
          when: 'Desayuno',
          name: 'Desayuno en el hotel',
          kind: 'Incluido',
          tip: 'Salida temprano hacia la Cruz del Cóndor.',
          q: 'Yanque, Caylloma',
        },
        {
          when: 'Almuerzo',
          name: 'Almuerzo en el valle del Colca',
          kind: 'Incluido',
          tip: 'Día largo de carretera: lleva agua y algo de picar.',
          q: 'Chivay',
        },
        {
          when: 'Qué probar',
          name: 'Platos típicos de Puno',
          kind: 'Trucha, ceviche de trucha, chairo, pesque de quinua, chicharrón de alpaca, kankacho',
          tip: 'Trucha del lago Titicaca, frita o a la parrilla. Chairo: sopa espesa de cordero o res con chuño. Pesque: puré de quinua con queso. Kankacho: cordero o lechón al horno.',
          q: 'restaurantes Puno',
        },
        {
          when: 'Cena libre',
          name: 'Mojsa Restaurante',
          kind: 'Cocina andina contemporánea · €€ · Centro',
          tip: 'Pide trucha (en ceviche o estofada) o lomo fino de alpaca. Reserva recomendada y confirma el horario de cena.',
          q: 'Mojsa Restaurante Puno',
        },
        {
          when: 'Cena libre',
          name: 'Balcones de Puno',
          kind: 'Peruana · €€ · Centro',
          tip: 'Carta sin verificar: úsalo como alternativa y pregunta por el plato del día.',
          q: 'Balcones de Puno Restaurante',
        },
      ],
      see: [
        {
          name: 'Cruz del Cóndor',
          desc: 'Observación de cóndores y vistas del cañón.',
          dur: 'Visita guiada',
          q: 'Mirador Cruz del Cóndor',
        },
        {
          name: 'Pinchollo',
          desc: 'Pueblo del valle del Colca en el recorrido hacia Maca.',
          dur: 'Parada en ruta',
          q: 'Pinchollo, Caylloma',
        },
        {
          name: 'Wayra Punku',
          desc: 'Pueblo del valle del Colca en el recorrido hacia Maca.',
          dur: 'Parada en ruta',
          q: 'Wayra Punku, Caylloma',
        },
        {
          name: 'Maca',
          desc: 'Pueblo del valle con iglesia colonial.',
          dur: 'Parada en ruta',
          q: 'Maca, Caylloma',
        },
        {
          name: 'Laguna de Lagunillas',
          desc: 'Laguna del altiplano camino de Puno.',
          dur: 'Parada en ruta',
          q: 'Laguna Lagunillas, Puno',
        },
      ],
    },
    {
      date: '2026-10-22',
      title: 'Lago Titicaca: Uros y Taquile',
      cities: ['Puno', 'Uros', 'Taquile'],
      stay: {
        name: 'Hotel en Puno',
        meta: 'Hotel pendiente de confirmar · segunda noche',
        q: 'Puno',
      },
      legs: [
        {
          mode: 'boat',
          title: 'Puno → Uros y Taquile',
          meta: 'Barco del circuito',
          q: 'Islas flotantes de los Uros',
        },
      ],
      plan: [
        {
          t: '08:00',
          title: 'Islas flotantes de los Uros',
          place: 'Lago Titicaca',
          q: 'Islas flotantes de los Uros',
        },
        {
          t: '09:30',
          title: 'Paseo en balsa de totora',
          place: 'Uros',
          q: 'Islas flotantes de los Uros',
        },
        { t: '11:30', title: 'Isla de Taquile', place: 'Lago Titicaca', q: 'Isla Taquile' },
        { t: '13:00', title: 'Almuerzo en la isla', place: 'Taquile', q: 'Isla Taquile' },
        { t: '17:00', title: 'Regreso al hotel', place: 'Puno', q: 'Puno' },
      ],
      eat: [
        {
          when: 'Desayuno',
          name: 'Desayuno en el hotel',
          kind: 'Incluido',
          tip: 'Salida temprano hacia los Uros.',
          q: 'Puno',
        },
        {
          when: 'Almuerzo',
          name: 'Almuerzo en Taquile',
          kind: 'Incluido',
          tip: 'Tiempo con la comunidad después de comer.',
          q: 'Isla Taquile',
        },
        {
          when: 'Cena libre',
          name: 'La Casona Restaurant',
          kind: 'Peruana · €€ · Centro',
          tip: 'Pide la trucha al ajillo o el chicharrón de trucha.',
          q: 'La Casona Restaurante Puno Calle Lima',
        },
        {
          when: 'Cena libre',
          name: 'Alma Bar Restaurante',
          kind: 'Cocina peruana de autor · €€€ · Fuera del centro',
          tip: 'Trucha y alpaca (platos concretos sin verificar). Ve en taxi; reserva recomendada.',
          q: 'Alma Bar Restaurante Puno',
        },
      ],
      see: [
        {
          name: 'Islas de los Uros',
          desc: 'Islas hechas de totora, con paseo en balsa.',
          dur: 'Visita guiada',
          q: 'Islas flotantes de los Uros',
        },
        {
          name: 'Isla de Taquile',
          desc: 'Técnica textil declarada Patrimonio de la Humanidad por la UNESCO.',
          dur: 'Visita guiada',
          q: 'Isla Taquile',
        },
      ],
    },
    {
      date: '2026-10-23',
      title: 'Puno → Cusco por la Ruta del Sur',
      cities: ['Puno', 'Pucará', 'La Raya', 'Raqchi', 'Andahuaylillas', 'Cusco'],
      stay: { name: 'Hotel en Cusco', meta: 'Centro · check-in desde 15:00', q: 'Cusco' },
      legs: [
        {
          mode: 'bus',
          title: 'Puno → Cusco',
          meta: 'Bus turístico · tasa de 0,5 $ por persona (pago directo)',
          from: 'Puno',
          to: 'Cusco',
        },
      ],
      plan: [
        { t: '07:00', title: 'Salida de Puno', place: 'Puno', q: 'Puno' },
        {
          t: '08:30',
          title: 'Pucará: museo, tradición y cultura',
          place: 'Pucará',
          q: 'Pucará, Puno',
        },
        { t: '11:00', title: 'Paso de La Raya (4.335 m)', place: 'La Raya', q: 'Abra La Raya' },
        {
          t: '13:00',
          title: 'Raqchi y Templo de Wiracocha',
          place: 'Raqchi',
          q: 'Complejo arqueológico de Raqchi',
        },
        { t: '14:00', title: 'Almuerzo', place: 'Ruta del Sur', q: 'Raqchi' },
        {
          t: '15:30',
          title: 'Iglesia de Andahuaylillas',
          place: 'Andahuaylillas',
          q: 'Iglesia de San Pedro Apóstol de Andahuaylillas',
        },
        { t: '17:30', title: 'Llegada a Cusco', place: 'Cusco', q: 'Cusco' },
      ],
      eat: [
        {
          when: 'Desayuno',
          name: 'Desayuno en el hotel',
          kind: 'Incluido',
          tip: 'Salida temprano de Puno: deja el equipaje listo.',
          q: 'Puno',
        },
        {
          when: 'Almuerzo',
          name: 'Almuerzo en la Ruta del Sur',
          kind: 'Incluido',
          tip: 'Lleva efectivo para la tasa del bus.',
          q: 'Raqchi',
        },
        {
          when: 'Qué probar',
          name: 'Platos típicos de Cusco',
          kind: 'Cuy al horno, adobo cusqueño, chicharrón con mote, kapchi de setas, sopa de quinua',
          tip: 'Cuy: en muchos locales hay que encargarlo con antelación. Adobo: cerdo macerado en chicha de jora. Kapchi: guiso cremoso de setas y habas, apto para vegetarianos.',
          q: 'restaurantes comida cusqueña Cusco',
        },
        {
          when: 'Cena libre',
          name: 'Chicha por Gastón Acurio',
          kind: 'Cocina cusqueña moderna · €€€ · Centro',
          tip: 'Pide cuy a la naranja, trucha o alpaca. Reserva con antelación en temporada alta.',
          q: 'Chicha por Gastón Acurio Cusco',
        },
      ],
      see: [
        {
          name: 'Pucará',
          desc: 'Museo y tradición alfarera.',
          dur: 'Parada en ruta',
          q: 'Pucará, Puno',
        },
        {
          name: 'Paso de La Raya',
          desc: 'Nevado Chimboya y los Andes a 4.335 m.',
          dur: 'Parada en ruta',
          q: 'Abra La Raya',
        },
        {
          name: 'Raqchi',
          desc: 'Templo de Wiracocha.',
          dur: 'Visita guiada',
          q: 'Complejo arqueológico de Raqchi',
        },
        {
          name: 'Andahuaylillas',
          desc: 'Iglesia barroca, la "Capilla Sixtina de América".',
          dur: 'Visita guiada',
          q: 'Iglesia de San Pedro Apóstol de Andahuaylillas',
        },
      ],
    },
    {
      date: '2026-10-24',
      title: 'Cusco',
      cities: ['Cusco'],
      stay: { name: 'Hotel en Cusco', meta: 'Centro · segunda noche', q: 'Cusco' },
      legs: [],
      plan: [
        {
          t: '09:00',
          title: 'Mercado de San Pedro',
          place: 'Cusco',
          q: 'Mercado de San Pedro, Cusco',
        },
        { t: '10:00', title: 'Koricancha', place: 'Cusco', q: 'Qorikancha, Cusco' },
        { t: '11:30', title: 'Fortaleza de Sacsayhuamán', place: 'Cusco', q: 'Sacsayhuamán' },
        { t: '12:30', title: 'Centro ceremonial de Kenko', place: 'Cusco', q: 'Qenqo, Cusco' },
        {
          t: '13:30',
          title: 'Catedral de Cusco',
          place: 'Plaza de Armas',
          q: 'Catedral del Cusco',
        },
        { t: '15:00', title: 'Tarde libre', place: 'Cusco', q: 'Plaza de Armas del Cusco' },
      ],
      eat: [
        {
          when: 'Desayuno',
          name: 'Desayuno en el hotel',
          kind: 'Incluido',
          tip: 'Tour de medio día: la tarde es libre.',
          q: 'Cusco',
        },
        {
          when: 'Comida libre',
          name: 'Morena Peruvian Kitchen',
          kind: 'Cocina peruana · €€ · Plaza de Armas',
          tip: 'Pide alpaca, ceviche o el ossobuco braseado. Reserva recomendada; búscalo por nombre en el mapa.',
          q: 'Morena Peruvian Kitchen Cusco',
        },
        {
          when: 'Cena',
          name: 'Cena libre en Cusco',
          kind: 'Por tu cuenta',
          tip: 'Prueba el lomo saltado o el ají de gallina.',
          q: 'restaurantes centro Cusco',
        },
        {
          when: 'Cena libre',
          name: 'Pachapapa',
          kind: 'Cocina cusqueña al horno de leña · €€ · San Blas',
          tip: 'Pide cuy (encárgalo con 24 h de antelación), kankacho o ají de gallina. Reserva recomendada.',
          q: 'Pachapapa Cusco San Blas',
        },
      ],
      see: [
        {
          name: 'Mercado de San Pedro',
          desc: 'Mercado central de la ciudad.',
          dur: 'Visita guiada',
          q: 'Mercado de San Pedro, Cusco',
        },
        {
          name: 'Koricancha',
          desc: 'Sincretismo inca y español.',
          dur: 'Visita guiada',
          q: 'Qorikancha, Cusco',
        },
        {
          name: 'Sacsayhuamán',
          desc: 'Fortaleza inca sobre la ciudad.',
          dur: 'Visita guiada',
          q: 'Sacsayhuamán',
        },
        {
          name: 'Kenko',
          desc: 'Centro ceremonial dentro del tour de medio día.',
          dur: 'Visita guiada',
          q: 'Qenqo, Cusco',
        },
        {
          name: 'Catedral de Cusco',
          desc: 'Arte colonial y orfebrería.',
          dur: 'Visita guiada',
          q: 'Catedral del Cusco',
        },
      ],
    },
    {
      date: '2026-10-25',
      title: 'Valle Sagrado → Aguas Calientes',
      cities: ['Cusco', 'Chinchero', 'Moray', 'Ollantaytambo', 'Aguas Calientes'],
      stay: {
        name: 'Hotel en Aguas Calientes',
        meta: 'Hotel pendiente de confirmar · solo equipaje de mano',
        q: 'Aguas Calientes',
      },
      legs: [
        {
          mode: 'bus',
          title: 'Cusco → Ollantaytambo',
          meta: 'Bus del circuito por el Valle Sagrado',
          from: 'Cusco',
          to: 'Ollantaytambo',
        },
        {
          mode: 'train',
          title: 'Ollantaytambo → Aguas Calientes',
          meta: 'Tren · máximo 5 kg de equipaje de mano por persona',
          from: 'Estación de tren de Ollantaytambo',
          to: 'Aguas Calientes',
          travel: 'transit',
        },
      ],
      plan: [
        {
          t: '08:00',
          title: 'Chinchero: tejidos y complejo arqueológico',
          place: 'Chinchero',
          q: 'Chinchero',
        },
        { t: '10:30', title: 'Terrazas de Moray', place: 'Moray', q: 'Moray, Maras' },
        {
          t: '13:00',
          title: 'Almuerzo en el Valle Sagrado',
          place: 'Valle Sagrado',
          q: 'Urubamba',
        },
        {
          t: '15:00',
          title: 'Fortaleza de Ollantaytambo',
          place: 'Ollantaytambo',
          q: 'Ollantaytambo',
        },
        {
          t: '17:30',
          title: 'Tren a Aguas Calientes',
          place: 'Estación de Ollantaytambo',
          q: 'Estación de tren de Ollantaytambo',
        },
        {
          t: '20:00',
          title: 'Cena en Aguas Calientes',
          place: 'Aguas Calientes',
          q: 'Aguas Calientes',
        },
      ],
      eat: [
        {
          when: 'Desayuno',
          name: 'Desayuno en el hotel',
          kind: 'Incluido',
          tip: 'Prepara solo el equipaje de mano para el tren.',
          q: 'Cusco',
        },
        {
          when: 'Almuerzo',
          name: 'Almuerzo en el Valle Sagrado',
          kind: 'Incluido',
          tip: 'Deja la maleta grande en el hotel de Cusco.',
          q: 'Urubamba',
        },
        {
          when: 'Cena',
          name: 'Cena en Aguas Calientes',
          kind: 'Incluida',
          tip: 'Acuéstate pronto: mañana toca Machu Picchu.',
          q: 'Aguas Calientes',
        },
      ],
      see: [
        {
          name: 'Chinchero',
          desc: 'Tejidos tradicionales y complejo arqueológico.',
          dur: 'Visita guiada',
          q: 'Chinchero',
        },
        {
          name: 'Moray',
          desc: 'Terrazas agrícolas incas.',
          dur: 'Visita guiada',
          q: 'Moray, Maras',
        },
        {
          name: 'Ollantaytambo',
          desc: 'Fortaleza inca con templos y calles originales.',
          dur: 'Visita guiada',
          q: 'Ollantaytambo',
        },
      ],
    },
    {
      date: '2026-10-26',
      title: 'Machu Picchu → Cusco',
      cities: ['Aguas Calientes', 'Machu Picchu', 'Ollantaytambo', 'Cusco'],
      stay: {
        name: 'Hotel en Cusco',
        meta: 'Centro · última noche · check-in desde 15:00',
        q: 'Cusco',
      },
      legs: [
        {
          mode: 'bus',
          title: 'Aguas Calientes → Machu Picchu',
          meta: 'Bus de subida',
          q: 'Machu Picchu',
        },
        {
          mode: 'train',
          title: 'Aguas Calientes → Ollantaytambo',
          meta: 'Tren de regreso',
          from: 'Aguas Calientes',
          to: 'Estación de tren de Ollantaytambo',
          travel: 'transit',
        },
        {
          mode: 'car',
          title: 'Ollantaytambo → Cusco',
          meta: 'Traslado por carretera',
          from: 'Ollantaytambo',
          to: 'Cusco',
        },
      ],
      plan: [
        {
          t: '07:00',
          title: 'Bus de subida a Machu Picchu',
          place: 'Aguas Calientes',
          q: 'Aguas Calientes',
        },
        {
          t: '08:00',
          title: 'Visita guiada a Machu Picchu',
          place: 'Machu Picchu',
          q: 'Machu Picchu',
        },
        {
          t: '12:30',
          title: 'Almuerzo en Aguas Calientes',
          place: 'Aguas Calientes',
          q: 'Aguas Calientes',
        },
        {
          t: '15:00',
          title: 'Tren de regreso y traslado a Cusco',
          place: 'Aguas Calientes',
          q: 'Estación de tren de Machu Picchu',
        },
        { t: '20:30', title: 'Cena de despedida', place: 'Cusco', q: 'Cusco' },
      ],
      eat: [
        {
          when: 'Desayuno',
          name: 'Desayuno en el hotel',
          kind: 'Incluido',
          tip: 'Madruga: el bus a Machu Picchu sale a primera hora.',
          q: 'Aguas Calientes',
        },
        {
          when: 'Almuerzo',
          name: 'Almuerzo en Aguas Calientes',
          kind: 'Incluido',
          tip: 'No se puede subir comida a Machu Picchu.',
          q: 'Aguas Calientes',
        },
        {
          when: 'Cena',
          name: 'Cena de despedida',
          kind: 'Incluida',
          tip: 'Última noche del circuito.',
          q: 'Cusco',
        },
      ],
      see: [
        {
          name: 'Machu Picchu',
          desc: 'Prohibido: trípodes, palos selfie, mochilas de más de 5 kg, comida y drones.',
          dur: 'Visita guiada',
          q: 'Machu Picchu',
        },
      ],
    },
    {
      date: '2026-10-27',
      title: 'Cusco → Lima → Madrid',
      cities: ['Cusco', 'Lima', 'Madrid'],
      stay: null,
      legs: [
        {
          mode: 'plane',
          title: 'Vuelo Cusco → Lima',
          meta: 'Sale 18:00 · llega 19:35',
          q: 'Aeropuerto Internacional Alejandro Velasco Astete',
        },
        {
          mode: 'plane',
          title: 'Vuelo Lima → Madrid',
          meta: 'Sale 21:05 · noche a bordo · conexión de 1 h 30 min',
          q: 'Aeropuerto Internacional Jorge Chávez',
        },
      ],
      plan: [
        {
          t: '09:00',
          title: 'Mañana libre en Cusco',
          place: 'Cusco',
          q: 'Plaza de Armas del Cusco',
        },
        {
          t: '15:00',
          title: 'Traslado al aeropuerto',
          place: 'Aeropuerto de Cusco',
          q: 'Aeropuerto Internacional Alejandro Velasco Astete',
        },
        {
          t: '18:00',
          title: 'Vuelo a Lima',
          place: 'Aeropuerto de Cusco',
          q: 'Aeropuerto Internacional Alejandro Velasco Astete',
        },
        {
          t: '21:05',
          title: 'Vuelo a Madrid',
          place: 'Aeropuerto Jorge Chávez',
          q: 'Aeropuerto Internacional Jorge Chávez',
        },
      ],
      eat: [
        {
          when: 'Desayuno',
          name: 'Desayuno en el hotel',
          kind: 'Incluido',
          tip: 'Lleva las dos tarjetas de embarque para la conexión en Lima.',
          q: 'Cusco',
        },
        {
          when: 'Comida libre',
          name: 'MAP Café',
          kind: 'Peruana creativa · €€€ · Centro',
          tip: 'Pide el kapchi de setas o el cuy. Reserva recomendada; ten en cuenta la hora del traslado al aeropuerto.',
          q: 'MAP Café Cusco',
        },
      ],
      see: [],
    },
    {
      date: '2026-10-28',
      title: 'Llegada a Madrid',
      cities: ['Madrid'],
      stay: null,
      legs: [],
      plan: [
        {
          t: '14:20',
          title: 'Llegada a Madrid',
          place: 'Aeropuerto de Madrid-Barajas',
          q: 'Aeropuerto Adolfo Suárez Madrid-Barajas',
        },
      ],
      eat: [],
      see: [],
    },
  ],
  checklist: [
    {
      key: 'g-hotel-puno',
      group: 'shared',
      label: 'Confirmar el hotel de Puno con la agencia',
      order: 1,
    },
    {
      key: 'g-hotel-aguas',
      group: 'shared',
      label: 'Confirmar el hotel de Aguas Calientes',
      order: 2,
    },
    {
      key: 'g-trenes',
      group: 'shared',
      label: 'Confirmar horarios de tren y hora de entrada a Machu Picchu',
      order: 3,
    },
    {
      key: 'g-catedral',
      group: 'shared',
      label: 'Confirmar la visita a la Catedral de Lima (domingo 18)',
      order: 4,
    },
    {
      key: 'g-conexion',
      group: 'shared',
      label: 'Confirmar si la facturación es directa hasta Madrid el 27',
      order: 5,
    },
    {
      key: 'g-traslados',
      group: 'shared',
      label: 'Confirmar con la agencia la hora de los traslados del 19 y del 27 oct',
      order: 6,
    },
    {
      key: 'g-checkin',
      group: 'shared',
      label: 'Check-in online de los vuelos (entre 48 h y 4 h antes)',
      order: 7,
    },
    {
      key: 'g-adaptador',
      group: 'shared',
      label: 'Adaptador de enchufe (tipos A, B y C)',
      order: 8,
    },
    {
      key: 'g-propinas',
      group: 'shared',
      label:
        'Dólares en efectivo para las propinas obligatorias (guías 3-4 USD y chófer 1-2 USD por persona y día)',
      order: 9,
    },
    {
      key: 'p-pasaporte',
      group: 'private',
      label: 'Pasaporte con al menos 6 meses de validez',
      order: 10,
    },
    { key: 'p-paginas', group: 'private', label: 'Pasaporte con páginas en blanco', order: 11 },
    {
      key: 'p-vacunas',
      group: 'private',
      label:
        'Libro de vacunación (certificado de fiebre amarilla solo si hay sello de un país endémico)',
      order: 12,
    },
    {
      key: 'p-billete-salida',
      group: 'private',
      label: 'Justificante de billete de regreso por si lo piden',
      order: 13,
    },
    {
      key: 'p-embarque',
      group: 'private',
      label: 'Las dos tarjetas de embarque para la conexión en Lima',
      order: 14,
    },
    {
      key: 'p-tuua',
      group: 'private',
      label:
        '12 US$ en efectivo por si cobran la tasa TUUA (si no se muestran las dos tarjetas de embarque)',
      order: 15,
    },
    {
      key: 'p-mochila',
      group: 'private',
      label: 'Mochila de mano de máximo 5 kg para el tren',
      order: 16,
    },
    { key: 'p-ropa', group: 'private', label: 'Ropa de abrigo por capas e impermeable', order: 17 },
    { key: 'p-calzado', group: 'private', label: 'Calzado de montaña', order: 18 },
    { key: 'p-sol', group: 'private', label: 'Protector solar y repelente', order: 19 },
  ],
}

export default content
