import type {
  CountryInfo,
  DailyPlan,
  DocumentItem,
  ItineraryItem,
  PackingItem,
  Place,
  PreTravelSection,
  Recommendation,
  Traveler,
} from '../types'

function uuid(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0
    const v = c === 'x' ? r : (r & 0x3) | 0x8
    return v.toString(16)
  })
}

function withTimestamps<T extends { id: string; createdAt: Date; updatedAt: Date }>(
  items: Omit<T, 'createdAt' | 'updatedAt'>[]
): T[] {
  return items.map((item) => ({ ...item, createdAt: now, updatedAt: now })) as T[]
}

export const travelers: Traveler[] = [
  { id: uuid(), name: 'Basilio Martin Sanz', passportNumber: 'PAF262178' },
  { id: uuid(), name: 'Maria Isabel Calvo Vaquerizo', passportNumber: 'PAF262177' },
  { id: uuid(), name: 'Borja Martin Calvo', passportNumber: 'PAP188120' },
  { id: uuid(), name: 'Nestor Martin Calvo', passportNumber: 'PAO904457' },
  { id: uuid(), name: 'Vanesa Pinillos Garcia', passportNumber: 'PAP704109' },
]

const now = new Date()

export const documents: DocumentItem[] = [
  {
    id: uuid(),
    type: 'flight',
    title: 'Vuelo IDA: MAD → DOH → HAN',
    data: {
      airline: 'Qatar Airways',
      departure: '2026-07-04T09:05:00+02:00',
      arrival: '2026-07-05T07:15:00+07:00',
      duration: '17h 10m',
      route: 'MAD → DOH → HAN',
      bookingReference: '',
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    type: 'flight',
    title: 'Vuelo VUELTA: PNH → AUH → MAD',
    data: {
      airline: 'Etihad Airways',
      departure: '2026-07-20T08:35:00+07:00',
      duration: '16h 05m',
      route: 'PNH → AUH → MAD',
      bookingReference: '',
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    type: 'flight',
    title: 'Vuelo INTERNO: DAD → SAI',
    data: {
      route: 'Da Nang (DAD) → Siem Reap (SAI)',
      departure: '2026-07-17',
      duration: '~1h 20m',
      note: 'Pendiente de reservar',
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    type: 'accommodation',
    title: 'Peridot Gallery Classic Hotel',
    data: {
      location: 'Old Quarter, Hanoi',
      nights: ['2026-07-05', '2026-07-12'],
      notes: '2 estancias separadas',
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    type: 'accommodation',
    title: 'Homestay Pu Luong',
    data: {
      location: 'Ban Hieu / Ban Don',
      nights: ['2026-07-06', '2026-07-07'],
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    type: 'accommodation',
    title: 'Tam Coc Family Hotel',
    data: {
      location: 'Tam Coc, Ninh Binh',
      nights: ['2026-07-08', '2026-07-09'],
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    type: 'accommodation',
    title: 'Cat Ba Eco Lodge',
    data: {
      location: 'Cat Ba',
      room: 'Deluxe Family Suite (2 dobles)',
      nights: ['2026-07-10', '2026-07-11'],
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    type: 'accommodation',
    title: 'Meliá Vinpearl Hue',
    data: {
      location: 'Hue',
      room: 'Two Bedroom Suite (1 king + 2 individuales)',
      night: '2026-07-14',
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    type: 'accommodation',
    title: 'An Bang Beach Town Homestay',
    data: {
      location: 'An Bang, Hoi An',
      nights: ['2026-07-15', '2026-07-16'],
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    type: 'accommodation',
    title: 'Khmer Mansion Boutique Hotel',
    data: {
      location: 'Wat Bo, Siem Reap',
      night: '2026-07-17',
    },
    createdAt: now,
    updatedAt: now,
  },
]

export const itineraryItems = withTimestamps<ItineraryItem>([
  {
    id: uuid(),
    date: '2026-07-04',
    startTime: '09:05',
    type: 'flight',
    title: 'Vuelo MAD → DOH → HAN',
    description: 'Salida desde Madrid con Qatar Airways. Escala en Doha.',
    notes: 'Llegada a Hanói el día 5 a las 07:15.',
    tags: ['vuelo', 'qatar', 'ida'],
  },
  {
    id: uuid(),
    date: '2026-07-05',
    startTime: '07:15',
    type: 'flight',
    title: 'Llegada a Hanói (HAN)',
    description: 'Llegada al aeropuerto Noi Bai de Hanói.',
    notes: 'Traslado al Old Quarter (~30 min, ~12 € con Grab).',
    tags: ['llegada', 'hanoi'],
  },
  {
    id: uuid(),
    date: '2026-07-05',
    startTime: '10:00',
    type: 'visit',
    title: 'Hanoi cultural',
    description: 'Paseo por el casco antiguo, lago Hoan Kiem y Templo de la Literatura.',
    location: { name: 'Hanoi Old Quarter', lat: 21.0341, lng: 105.8494 },
    tags: ['hanoi', 'cultura'],
  },
  {
    id: uuid(),
    date: '2026-07-05',
    startTime: '15:00',
    type: 'activity',
    title: 'Café con huevo en Giang Café',
    location: { name: 'Giang Café', lat: 21.0326, lng: 105.8544 },
    tags: ['hanoi', 'café', 'gastronomía'],
  },
  {
    id: uuid(),
    date: '2026-07-05',
    startTime: '14:00',
    endTime: '12:00',
    type: 'accommodation',
    title: 'Peridot Gallery Classic Hotel',
    description: 'Check-in y check-out del hotel en el Old Quarter.',
    location: { name: 'Peridot Gallery Classic Hotel, Old Quarter, Hanoi', lat: 21.0345, lng: 105.852 },
    tags: ['hanoi', 'alojamiento'],
  },
  {
    id: uuid(),
    date: '2026-07-06',
    startTime: '08:00',
    type: 'transport',
    title: 'Hanoi → Pu Luong',
    description: 'Traslado en coche privado.',
    notes: 'Duración estimada 3,5-4 h. Salida a las 8:00.',
    tags: ['transporte', 'pu-luong'],
  },
  {
    id: uuid(),
    date: '2026-07-06',
    startTime: '13:00',
    endTime: '11:00',
    type: 'accommodation',
    title: 'Homestay Pu Luong',
    description: 'Llegada al homestay en Ban Hieu.',
    location: { name: 'Homestay Pu Luong, Ban Hieu / Ban Don', lat: 20.475, lng: 105.2436 },
    tags: ['pu-luong', 'alojamiento'],
  },
  {
    id: uuid(),
    date: '2026-07-07',
    startTime: '08:00',
    type: 'activity',
    title: 'Trekking por Pu Luong',
    description: 'Ruta por arrozales en terrazas y cascada Hieu.',
    location: { name: 'Hieu Waterfall', lat: 20.4408, lng: 105.2692 },
    tags: ['pu-luong', 'trekking', 'naturaleza'],
  },
  {
    id: uuid(),
    date: '2026-07-08',
    startTime: '09:00',
    type: 'transport',
    title: 'Pu Luong → Ninh Binh / Tam Coc',
    description: 'Coche privado hasta Tam Coc.',
    notes: 'Duración estimada ~3 h.',
    tags: ['transporte', 'ninh-binh'],
  },
  {
    id: uuid(),
    date: '2026-07-08',
    startTime: '14:00',
    endTime: '12:00',
    type: 'accommodation',
    title: 'Tam Coc Family Hotel',
    description: 'Check-in en Tam Coc.',
    location: { name: 'Tam Coc Family Hotel, Tam Coc, Ninh Binh', lat: 20.2465, lng: 105.9356 },
    tags: ['ninh-binh', 'alojamiento'],
  },
  {
    id: uuid(),
    date: '2026-07-09',
    startTime: '07:00',
    type: 'visit',
    title: 'Trang An',
    description: 'Paseo en barca por el complejo kárstico de Trang An (UNESCO).',
    location: { name: 'Trang An', lat: 20.2546, lng: 105.9234 },
    notes: 'Madrugar para evitar colas de autocares (10-11 h).',
    tags: ['ninh-binh', 'unesco', 'barca'],
  },
  {
    id: uuid(),
    date: '2026-07-09',
    startTime: '14:00',
    type: 'activity',
    title: 'Hang Mua',
    description: 'Subida de 500 escalones con vistas panorámicas de 360°.',
    location: { name: 'Hang Mua', lat: 20.2364, lng: 105.9386 },
    tags: ['ninh-binh', 'vistas', 'trekking'],
  },
  {
    id: uuid(),
    date: '2026-07-10',
    startTime: '08:00',
    type: 'transport',
    title: 'Ninh Binh → Cat Ba',
    description: 'Coche 2 h + ferry 45 min.',
    notes: 'Salida a las 8:00.',
    tags: ['transporte', 'cat-ba'],
  },
  {
    id: uuid(),
    date: '2026-07-10',
    startTime: '13:00',
    endTime: '12:00',
    type: 'accommodation',
    title: 'Cat Ba Eco Lodge',
    description: 'Check-in en Cat Ba.',
    location: { name: 'Cat Ba Eco Lodge, Cat Ba', lat: 20.7692, lng: 107.0456 },
    tags: ['cat-ba', 'alojamiento'],
  },
  {
    id: uuid(),
    date: '2026-07-11',
    startTime: '08:00',
    type: 'activity',
    title: 'Lan Ha Bay en kayak',
    description: 'Excursión en barco y kayak por lagunas escondidas.',
    location: { name: 'Beo Dock', lat: 20.7275, lng: 107.075 },
    notes: 'Salida desde el muelle Beo a las 8:00. Mucho menos barcos que Ha Long.',
    tags: ['cat-ba', 'lan-ha-bay', 'kayak'],
  },
  {
    id: uuid(),
    date: '2026-07-12',
    startTime: '10:00',
    type: 'transport',
    title: 'Cat Ba → Hanói',
    description: 'Ferry 45 min + coche 3,5 h.',
    tags: ['transporte', 'hanoi'],
  },
  {
    id: uuid(),
    date: '2026-07-12',
    startTime: '16:00',
    endTime: '12:00',
    type: 'accommodation',
    title: '2ª noche en Peridot Gallery Classic Hotel',
    description: 'Segunda estancia en el Old Quarter de Hanói.',
    location: { name: 'Peridot Gallery Classic Hotel, Old Quarter, Hanoi', lat: 21.0345, lng: 105.852 },
    tags: ['hanoi', 'alojamiento'],
  },
  {
    id: uuid(),
    date: '2026-07-13',
    startTime: '09:00',
    type: 'visit',
    title: 'Hanoi extra',
    description: 'Mañana libre para completar visitas pendientes.',
    tags: ['hanoi', 'cultura'],
  },
  {
    id: uuid(),
    date: '2026-07-13',
    startTime: '22:00',
    type: 'transport',
    title: 'Tren nocturno Hanói → Hue',
    description: 'Reunification Express, camarote VIP 4 literas.',
    notes: 'Duración ~14 h. Pendiente reservar en Vexere/Baolau (~25-35 €/pers).',
    tags: ['transporte', 'tren', 'hue'],
  },
  {
    id: uuid(),
    date: '2026-07-14',
    startTime: '12:00',
    type: 'transport',
    title: 'Llegada a Hue',
    description: 'Llegada estimada a la estación de tren de Hue.',
    tags: ['llegada', 'hue'],
  },
  {
    id: uuid(),
    date: '2026-07-14',
    startTime: '15:00',
    type: 'visit',
    title: 'Ciudad Imperial de Hue',
    description: 'Recorrido por la antigua capital imperial Nguyen (UNESCO).',
    location: { name: 'Imperial City', lat: 16.4697, lng: 107.5778 },
    tags: ['hue', 'unesco', 'cultura'],
  },
  {
    id: uuid(),
    date: '2026-07-14',
    startTime: '15:00',
    endTime: '12:00',
    type: 'accommodation',
    title: 'Meliá Vinpearl Hue',
    description: 'Check-in en Hue.',
    location: { name: 'Meliá Vinpearl Hue, Hue', lat: 16.4631, lng: 107.5908 },
    tags: ['hue', 'alojamiento'],
  },
  {
    id: uuid(),
    date: '2026-07-15',
    startTime: '08:00',
    type: 'visit',
    title: 'Tumbas imperiales',
    description: 'Tumbas Khai Dinh y Tu Duc.',
    location: { name: 'Tomb of Khai Dinh', lat: 16.3995, lng: 107.5902 },
    tags: ['hue', 'tumbas', 'cultura'],
  },
  {
    id: uuid(),
    date: '2026-07-15',
    startTime: '11:00',
    type: 'visit',
    title: 'Pagoda Thien Mu',
    location: { name: 'Thien Mu Pagoda', lat: 16.4537, lng: 107.5421 },
    tags: ['hue', 'templo'],
  },
  {
    id: uuid(),
    date: '2026-07-15',
    startTime: '15:00',
    type: 'transport',
    title: 'Hue → Hoi An',
    description: 'Autobús ~3 h por el Paso de Hai Van.',
    tags: ['transporte', 'hoi-an'],
  },
  {
    id: uuid(),
    date: '2026-07-15',
    startTime: '19:00',
    endTime: '12:00',
    type: 'accommodation',
    title: 'An Bang Beach Town Homestay',
    description: 'Check-in en An Bang, Hoi An.',
    location: { name: 'An Bang Beach Town Homestay, An Bang, Hoi An', lat: 15.9108, lng: 108.3783 },
    tags: ['hoi-an', 'alojamiento'],
  },
  {
    id: uuid(),
    date: '2026-07-16',
    startTime: '08:00',
    type: 'visit',
    title: 'Casco antiguo de Hoi An',
    description: 'Paseo matutino sin aglomeraciones por el casco antiguo (UNESCO).',
    location: { name: 'Hoi An Ancient Town', lat: 15.8801, lng: 108.338 },
    tags: ['hoi-an', 'unesco', 'cultura'],
  },
  {
    id: uuid(),
    date: '2026-07-16',
    startTime: '11:00',
    type: 'activity',
    title: 'Taller de linternas de seda',
    location: { name: 'Hoi An Ancient Town', lat: 15.879, lng: 108.335 },
    tags: ['hoi-an', 'artesanía'],
  },
  {
    id: uuid(),
    date: '2026-07-17',
    startTime: '09:00',
    type: 'visit',
    title: 'Mañana libre en Hoi An',
    tags: ['hoi-an'],
  },
  {
    id: uuid(),
    date: '2026-07-17',
    startTime: '14:00',
    type: 'transport',
    title: 'Traslado Hoi An → Aeropuerto Da Nang',
    description: 'Taxi ~45 min (~15 € con Grab).',
    tags: ['transporte', 'da-nang'],
  },
  {
    id: uuid(),
    date: '2026-07-17',
    startTime: '17:00',
    type: 'flight',
    title: 'Vuelo DAD → SAI',
    description: 'Vuelo directo Da Nang a Siem Reap.',
    notes: 'Duración ~1 h 20 min. Pendiente de reservar.',
    tags: ['vuelo', 'siem-reap'],
  },
  {
    id: uuid(),
    date: '2026-07-17',
    startTime: '20:00',
    endTime: '12:00',
    type: 'accommodation',
    title: 'Khmer Mansion Boutique Hotel',
    description: 'Check-in en Siem Reap.',
    location: { name: 'Khmer Mansion Boutique Hotel, Wat Bo, Siem Reap', lat: 13.3612, lng: 103.8634 },
    tags: ['siem-reap', 'alojamiento'],
  },
  {
    id: uuid(),
    date: '2026-07-18',
    startTime: '05:00',
    type: 'visit',
    title: 'Amanecer en Srah Srang',
    description: 'Amanecer tranquilo lejos de las multitudes de Angkor Wat.',
    location: { name: 'Srah Srang', lat: 13.4017, lng: 103.9181 },
    tags: ['siem-reap', 'angkor', 'amanecer'],
  },
  {
    id: uuid(),
    date: '2026-07-18',
    startTime: '08:00',
    type: 'visit',
    title: 'Angkor circuito grande',
    description: 'Bayon, Ta Prohm y otros templos principales.',
    location: { name: 'Angkor Thom', lat: 13.4413, lng: 103.8586 },
    notes: 'Tuk-tuk todo el día (~15-20 USD). Pase 3 días 62 USD/pers.',
    tags: ['siem-reap', 'angkor', 'templos'],
  },
  {
    id: uuid(),
    date: '2026-07-19',
    startTime: '08:00',
    type: 'visit',
    title: 'Banteay Srei',
    description: 'Templo rosa con las tallas más finas de Angkor.',
    location: { name: 'Banteay Srei', lat: 13.5989, lng: 103.9628 },
    tags: ['siem-reap', 'angkor', 'templos'],
  },
  {
    id: uuid(),
    date: '2026-07-19',
    startTime: '14:00',
    type: 'activity',
    title: 'Kbal Spean (río de los 1000 lingas)',
    location: { name: 'Kbal Spean', lat: 13.6906, lng: 103.9681 },
    tags: ['siem-reap', 'angkor', 'naturaleza'],
  },
  {
    id: uuid(),
    date: '2026-07-19',
    startTime: '22:00',
    type: 'transport',
    title: 'Bus nocturno Siem Reap → Phnom Penh',
    description: 'Bus nocturno VIP cama.',
    notes: 'Duración ~6 h. Pendiente reservar en BookMeBus/VET (22:00-23:00).',
    tags: ['transporte', 'bus', 'phnom-penh'],
  },
  {
    id: uuid(),
    date: '2026-07-20',
    startTime: '08:35',
    type: 'flight',
    title: 'Vuelo PNH → MAD',
    description: 'Salida desde Phnom Penh con Etihad Airways.',
    notes: 'Escala en Abu Dhabi. Llegada a Madrid el mismo día.',
    tags: ['vuelo', 'vuelta'],
  },
])

export const places = withTimestamps<Place>([
  {
    id: uuid(),
    name: 'Hanoi Old Quarter',
    description:
      'Laberinto de calles del casco antiguo de Hanói con arquitectura colonial y comercios tradicionales.',
    category: 'city',
    location: { name: 'Hanoi Old Quarter', lat: 21.0341, lng: 105.8494 },
    tips: ['Madrugar para evitar el tráfico de motos', 'Probar pho y bun cha en puestos locales'],
  },
  {
    id: uuid(),
    name: 'Temple of Literature',
    description: 'Primera universidad de Vietnam, fundada en 1070.',
    category: 'temple',
    location: { name: 'Temple of Literature', lat: 21.0287, lng: 105.8356 },
    tips: ['Llevar ropa que cubra hombros y rodillas'],
  },
  {
    id: uuid(),
    name: 'Hoan Kiem Lake',
    description:
      'Lago sagrado en el corazón de Hanói, con la leyenda de la espada devuelta a la tortuga.',
    category: 'nature',
    location: { name: 'Hoan Kiem Lake', lat: 21.0288, lng: 105.8521 },
  },
  {
    id: uuid(),
    name: 'Ho Chi Minh Mausoleum',
    description: 'Mausoleo donde descansa el líder fundador de Vietnam.',
    category: 'museum',
    location: { name: 'Ho Chi Minh Mausoleum', lat: 21.0369, lng: 105.8346 },
    tips: ['Horario estricto y vestimenta conservadora'],
  },
  {
    id: uuid(),
    name: 'One Pillar Pagoda',
    description: 'Pagoda histórica del siglo VI sobre un solo pilar de madera.',
    category: 'temple',
    location: { name: 'One Pillar Pagoda', lat: 21.0358, lng: 105.8336 },
  },
  {
    id: uuid(),
    name: 'Giang Café',
    description: 'Café histórico famoso por el café con huevo de Hanói.',
    category: 'restaurant',
    location: { name: 'Giang Café', lat: 21.0326, lng: 105.8544 },
    tips: ['Probar el egg coffee original'],
  },
  {
    id: uuid(),
    name: 'Pu Luong Nature Reserve',
    description: 'Reserva natural con arrozales en terrazas y montañas kársticas.',
    category: 'nature',
    location: { name: 'Pu Luong Nature Reserve', lat: 20.475, lng: 105.2436 },
    tips: ['90 % menos turistas que Sapa', 'Contratar coche con el homestay'],
  },
  {
    id: uuid(),
    name: 'Hieu Waterfall',
    description: 'Cascada en plena selva de Pu Luong, accesible en trekking.',
    category: 'nature',
    location: { name: 'Hieu Waterfall', lat: 20.4408, lng: 105.2692 },
  },
  {
    id: uuid(),
    name: 'Thai and Muong Villages',
    description: 'Aldeas de las etnias Thai y Muong con casas sobre pilotes.',
    category: 'city',
    location: { name: 'Ban Hieu / Ban Don', lat: 20.456, lng: 105.255 },
  },
  {
    id: uuid(),
    name: 'Trang An',
    description: 'Paisaje kárstico UNESCO con cuevas y templos accesibles en barca.',
    category: 'nature',
    location: { name: 'Trang An', lat: 20.2546, lng: 105.9234 },
    tips: ['Llegar a las 7:00 para evitar colas'],
  },
  {
    id: uuid(),
    name: 'Hang Mua',
    description: 'Mirador con 500 escalones y vistas de 360° sobre Ninh Binh.',
    category: 'nature',
    location: { name: 'Hang Mua', lat: 20.2364, lng: 105.9386 },
    tips: ['Subida pronunciada, llevar calzado cómodo'],
  },
  {
    id: uuid(),
    name: 'Tam Coc',
    description: 'Paseo en barca por el río Ngo Dong entre formaciones kársticas.',
    category: 'nature',
    location: { name: 'Tam Coc', lat: 20.2465, lng: 105.9356 },
  },
  {
    id: uuid(),
    name: 'Bich Dong',
    description: 'Complejo de pagodas construidas en la ladera de una montaña.',
    category: 'temple',
    location: { name: 'Bich Dong', lat: 20.2294, lng: 105.9389 },
  },
  {
    id: uuid(),
    name: 'Beo Dock',
    description: 'Muelle de salida para excursiones a Lan Ha Bay.',
    category: 'nature',
    location: { name: 'Beo Dock', lat: 20.7275, lng: 107.075 },
    tips: ['Salidas tempranas a las 8:00'],
  },
  {
    id: uuid(),
    name: 'Viet Hai Floating Village',
    description: 'Aldea flotante tranquila en Lan Ha Bay.',
    category: 'city',
    location: { name: 'Viet Hai', lat: 20.7583, lng: 107.0083 },
  },
  {
    id: uuid(),
    name: 'Cat Co Beaches',
    description: 'Playas de arena blanca y agua templada en Cat Ba.',
    category: 'beach',
    location: { name: 'Cat Co Beaches', lat: 20.725, lng: 107.054 },
  },
  {
    id: uuid(),
    name: 'Imperial City',
    description: 'Ciudadela imperial de la dinastía Nguyen, patrimonio UNESCO.',
    category: 'museum',
    location: { name: 'Imperial City', lat: 16.4697, lng: 107.5778 },
    tips: ['Primera hora de la tarde suele haber menos gente'],
  },
  {
    id: uuid(),
    name: 'Tomb of Khai Dinh',
    description: 'Tumba imperial con influencias vietnamitas, china y europea.',
    category: 'temple',
    location: { name: 'Tomb of Khai Dinh', lat: 16.3995, lng: 107.5902 },
  },
  {
    id: uuid(),
    name: 'Tomb of Tu Duc',
    description: 'Tumba del emperador Tu Duc en un parque arbolado.',
    category: 'temple',
    location: { name: 'Tomb of Tu Duc', lat: 16.43, lng: 107.5658 },
  },
  {
    id: uuid(),
    name: 'Thien Mu Pagoda',
    description: 'Pagoda de siete pisos junto al río Perfume, símbolo de Hue.',
    category: 'temple',
    location: { name: 'Thien Mu Pagoda', lat: 16.4537, lng: 107.5421 },
  },
  {
    id: uuid(),
    name: 'Perfume River',
    description: 'Río Huong que cruza Hue y da un marco romántico a la ciudad.',
    category: 'nature',
    location: { name: 'Perfume River', lat: 16.4667, lng: 107.6 },
  },
  {
    id: uuid(),
    name: 'Hoi An Ancient Town',
    description: 'Casco antiguo UNESCO con arquitectura china, japonesa y francesa.',
    category: 'city',
    location: { name: 'Hoi An Ancient Town', lat: 15.8801, lng: 108.338 },
    tips: ['Entrar a las 8:00 para disfrutar sin aglomeraciones'],
  },
  {
    id: uuid(),
    name: 'Japanese Covered Bridge',
    description: 'Puente japonés del siglo XVII con pagoda.',
    category: 'temple',
    location: { name: 'Japanese Covered Bridge', lat: 15.8777, lng: 108.3346 },
  },
  {
    id: uuid(),
    name: 'An Bang Beach',
    description: 'Plaia tranquila en el Mar de China Meridional cerca de Hoi An.',
    category: 'beach',
    location: { name: 'An Bang Beach', lat: 15.9108, lng: 108.3783 },
  },
  {
    id: uuid(),
    name: 'Tra Que Vegetable Village',
    description: 'Aldea agrícola famosa por sus hierbas y verduras orgánicas.',
    category: 'city',
    location: { name: 'Tra Que', lat: 15.9012, lng: 108.3556 },
  },
  {
    id: uuid(),
    name: 'Marble Mountains',
    description: 'Cinco colinas de mármol con cuevas y pagodas budistas cerca de Da Nang.',
    category: 'nature',
    location: { name: 'Marble Mountains', lat: 16.0313, lng: 108.2164 },
  },
  {
    id: uuid(),
    name: 'Angkor Wat',
    description: 'Mayor complejo religioso del mundo, construido en el siglo XII.',
    category: 'temple',
    location: { name: 'Angkor Wat', lat: 13.4125, lng: 103.8667 },
    tips: ['Evitar amanecer en Angkor Wat; mejor ir a Srah Srang'],
  },
  {
    id: uuid(),
    name: 'Bayon',
    description: 'Templo de Angkor Thom con 216 caras sonrientes de Avalokiteshvara.',
    category: 'temple',
    location: { name: 'Bayon', lat: 13.4413, lng: 103.8586 },
  },
  {
    id: uuid(),
    name: 'Ta Prohm',
    description: 'Templo abrazado por raíces de árboles, famoso por Tomb Raider.',
    category: 'temple',
    location: { name: 'Ta Prohm', lat: 13.435, lng: 103.8895 },
  },
  {
    id: uuid(),
    name: 'Srah Srang',
    description: 'Piscina sagrada y mirador de amanecer sin multitudes.',
    category: 'nature',
    location: { name: 'Srah Srang', lat: 13.4017, lng: 103.9181 },
    tips: ['Mejor alternativa al amanecer de Angkor Wat'],
  },
  {
    id: uuid(),
    name: 'Banteay Srei',
    description: 'Templo rosa con las tallas más finas y detalladas de Angkor.',
    category: 'temple',
    location: { name: 'Banteay Srei', lat: 13.5989, lng: 103.9628 },
  },
  {
    id: uuid(),
    name: 'Kbal Spean',
    description: 'Río con más de 1000 lingas tallados en el lecho de roca.',
    category: 'nature',
    location: { name: 'Kbal Spean', lat: 13.6906, lng: 103.9681 },
  },
  {
    id: uuid(),
    name: 'Kampong Phluk',
    description: 'Aldea flotante auténtica en el lago Tonlé Sap.',
    category: 'city',
    location: { name: 'Kampong Phluk', lat: 13.2019, lng: 104.0114 },
  },
])

export const countryInfo: CountryInfo[] = [
  {
    id: uuid(),
    country: 'vietnam',
    sections: {
      history:
        'Vietnam tiene una historia milenaria con influencias chinas, francesas y propias. Destacan la Ciudad Imperial de Hue, la antigua capital de Ninh Binh (siglos X-XI) y la Pagoda de un Pilar del siglo VI.',
      culture:
        'Cultura profundamente arraigada en el confucianismo, el budismo y el culto a los antepasados. Las ciudades antiguas, templos y pagodas son centros espirituales y sociales.',
      food: 'Gastronomía fresca y equilibrada: pho, bun cha, bun bo Hue, bánh mì, café con huevo (Giang Café), Cao Lau en Hoi An y marisco fresco en Cat Ba.',
      traditions:
        'Festividades como el Tet (Año Nuevo lunar), ofrendas en templos, farolillos de seda en Hoi An y artesanías tradicionales en aldeas como Tra Que.',
      customs:
        'Saludo sutil con las manos juntas, quitarse los zapatos al entrar en templos y hogares, y vestimenta conservadora en lugares sagrados (hombros y rodillas cubiertos).',
      language:
        'Vietnamita es una lengua tonal. Frases útiles: Xin chào (hola), Cảm ơn (gracias), Bao nhiêu? (¿cuánto cuesta?), Không (no).',
      currency:
        'Dong vietnamita (VND). 1 € ≈ 27.000 VND. Se usa principalmente efectivo; pocos comercios aceptan tarjeta.',
      tips: [
        'Descargar Grab para desplazamientos urbanos',
        'Negociar precios en mercados y con tuk-tuks',
        'Llevar efectivo en VND',
        'Madrugar en sitios turísticos para evitar colas',
      ],
    },
  },
  {
    id: uuid(),
    country: 'cambodia',
    sections: {
      history:
        'Antiguo Imperio Jemer (siglos IX-XV), cuyo máximo exponente es Angkor. Período trágico del Jemer Rojo (1975-1979). Phnom Penh es la capital actual.',
      culture:
        'Budismo theravada, sonrisa tradicional camboyana y fuerte sentido de comunidad. Los templos son el corazón espiritual del país.',
      food: 'Platos típicos: fish amok, lok lak, riel (sopa), arroz pegajoso y fruta fresca. Influencias tailandesas y vietnamitas.',
      traditions:
        'Festividades budistas, ofrendas en templos, artesanías de seda y tradición de danza Apsara.',
      customs:
        'Reverencia hacia los monjes, cubrir hombros y rodillas en templos, y no tocar la cabeza de otras personas.',
      language:
        'Jemer (khmer). Frases útiles: Chum reap suor (hola), Arkun (gracias), Tlay pon (muy caro), Baht (suficiente).',
      currency:
        'Dólar USD es la moneda principal; los riels solo se usan para cambio menor. Llevar billetes pequeños y en buen estado.',
      tips: [
        'Pase Angkor de 3 días cuesta 62 USD/persona',
        'Tuk-tuk en Siem Reap: 15-20 USD/día',
        'Amanecer en Srah Srang o Pre Rup, no en Angkor Wat',
        'E-visa de Camboya ~30 USD; llevar foto tamaño carnet',
      ],
    },
  },
]

export const packingItems: PackingItem[] = [
  // documents
  {
    id: uuid(),
    category: 'documents',
    name: 'Pasaporte (vigencia > 6 meses)',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'documents',
    name: 'Visado e-visa Vietnam',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'documents',
    name: 'Visado Camboya (e-visa o visa on arrival)',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'documents',
    name: 'Seguro de viaje (impreso + digital)',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'documents',
    name: 'Billetes de avión (ida y vuelta)',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'documents',
    name: 'Reservas de alojamiento',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'documents',
    name: 'Fotos tamaño carnet (visados)',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'documents',
    name: 'Copias de documentos (digital + físico)',
    checked: false,
    essential: true,
  },
  // health
  { id: uuid(), category: 'health', name: 'Cartilla de vacunas', checked: false, essential: true },
  {
    id: uuid(),
    category: 'health',
    name: 'Medicamentos básicos (paracetamol, ibuprofeno, antidiarreico)',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'health',
    name: 'Repelente de insectos',
    checked: false,
    essential: true,
  },
  { id: uuid(), category: 'health', name: 'Protector solar', checked: false, essential: true },
  {
    id: uuid(),
    category: 'health',
    name: 'Botiquín personalizado',
    checked: false,
    essential: false,
  },
  {
    id: uuid(),
    category: 'health',
    name: 'Recetas médicas (si aplica)',
    checked: false,
    essential: false,
  },
  // clothing
  {
    id: uuid(),
    category: 'clothing',
    name: 'Ropa ligera y transpirable',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'clothing',
    name: 'Impermeable / chubasquero',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'clothing',
    name: 'Calzado cómodo para caminar',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'clothing',
    name: 'Ropa para templos (hombros y rodillas cubiertos)',
    checked: false,
    essential: true,
  },
  { id: uuid(), category: 'clothing', name: 'Bañador', checked: false, essential: true },
  { id: uuid(), category: 'clothing', name: 'Chanclas', checked: false, essential: false },
  // electronics
  {
    id: uuid(),
    category: 'electronics',
    name: 'Adaptador de enchufe (tipo A/C/O/M)',
    checked: false,
    essential: true,
  },
  { id: uuid(), category: 'electronics', name: 'Power bank', checked: false, essential: true },
  {
    id: uuid(),
    category: 'electronics',
    name: 'Cables y cargadores',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'electronics',
    name: 'Tarjeta SD / memoria extra',
    checked: false,
    essential: false,
  },
  { id: uuid(), category: 'electronics', name: 'Auriculares', checked: false, essential: false },
  // toiletries
  {
    id: uuid(),
    category: 'toiletries',
    name: 'Toalla de microfibra',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'toiletries',
    name: 'Gel hidroalcohólico',
    checked: false,
    essential: true,
  },
  { id: uuid(), category: 'toiletries', name: 'Pañuelos húmedos', checked: false, essential: true },
  // misc
  { id: uuid(), category: 'misc', name: 'Candado para mochila', checked: false, essential: false },
  {
    id: uuid(),
    category: 'misc',
    name: 'Bolsa estanca para electrónicos',
    checked: false,
    essential: true,
  },
  {
    id: uuid(),
    category: 'misc',
    name: 'Dinero en efectivo (USD + VND)',
    checked: false,
    essential: true,
  },
]

export const preTravelSections: PreTravelSection[] = [
  {
    id: uuid(),
    category: 'vaccines',
    title: 'Vacunas y salud',
    items: [
      {
        id: uuid(),
        text: 'Vacunas recomendadas',
        important: true,
        details:
          'Hepatitis A/B, tifoidea, tétanos. Rabia solo si se va a zonas rurales prolongadas.',
      },
      {
        id: uuid(),
        text: 'Medicamentos básicos',
        important: true,
        details: 'Paracetamol, ibuprofeno, antidiarreico, antibiótico de viaje (receta).',
      },
      { id: uuid(), text: 'Agua embotellada siempre', important: true },
      {
        id: uuid(),
        text: 'Comida callejera: elegir puestos con mucha clientela local',
        important: false,
      },
    ],
  },
  {
    id: uuid(),
    category: 'money',
    title: 'Dinero y pagos',
    items: [
      {
        id: uuid(),
        text: 'Vietnam: llevar VND en efectivo',
        important: true,
        details: '1 € ≈ 27.000 VND. Pocos sitios aceptan tarjeta.',
      },
      {
        id: uuid(),
        text: 'Camboya: llevar USD en billetes pequeños y en buen estado',
        important: true,
        details: 'Riel solo para cambio menor (< 1 USD).',
      },
      { id: uuid(), text: 'Tarjetas sin comisiones por extracción', important: false },
      { id: uuid(), text: 'Avisar al banco del viaje', important: true },
    ],
  },
  {
    id: uuid(),
    category: 'connectivity',
    title: 'Conectividad',
    items: [
      { id: uuid(), text: 'Vietnam: SIM Viettel (~5-10 USD con datos)', important: true },
      { id: uuid(), text: 'Camboya: SIM Cellcard o Smart', important: true },
      { id: uuid(), text: 'Descargar mapas offline de Google Maps', important: true },
      { id: uuid(), text: 'Apps útiles: Grab, Google Translate offline', important: false },
    ],
  },
  {
    id: uuid(),
    category: 'safety',
    title: 'Seguridad',
    items: [
      {
        id: uuid(),
        text: 'Números de emergencia: Vietnam 113/115, Camboya 117/119',
        important: true,
      },
      {
        id: uuid(),
        text: 'Estafas comunes',
        important: true,
        details: 'Tuk-tuks sin taxímetro, precios inflados en mercados, cambio incorrecto.',
      },
      { id: uuid(), text: 'Guardar copia digital del pasaporte en la nube', important: true },
      { id: uuid(), text: 'Evitar mostrar objetos de valor', important: false },
    ],
  },
  {
    id: uuid(),
    category: 'tips',
    title: 'Consejos prácticos',
    items: [
      {
        id: uuid(),
        text: 'Clima en julio',
        important: true,
        details:
          'Temporada de lluvias monzónicas. Chaparrones cortos por la tarde, arrozales en máximo esplendor.',
      },
      { id: uuid(), text: 'Transporte: Grab en ciudades, tuk-tuk en Camboya', important: false },
      { id: uuid(), text: 'Negociar en mercados (empezar al 50 % del precio)', important: false },
      { id: uuid(), text: 'Templos: cubrir hombros y rodillas, quitarse zapatos', important: true },
    ],
  },
]

export const recommendations = withTimestamps<Recommendation>([
  {
    id: uuid(),
    type: 'activity',
    title: 'Café con huevo en Giang Café',
    description: 'Experiencia gastronómica imprescindible en Hanói.',
    location: { name: 'Giang Café', lat: 21.0326, lng: 105.8544 },
    tags: ['hanoi', 'gastronomía', 'café'],
    priority: 'must-see',
  },
  {
    id: uuid(),
    type: 'place',
    title: 'Mercado Dong Xuan',
    description: 'Mercado cubierto más grande de Hanói, ideal para souvenirs y ver vida local.',
    location: { name: 'Dong Xuan Market', lat: 21.0378, lng: 105.85 },
    tags: ['hanoi', 'mercado', 'compras'],
    priority: 'if-time',
  },
  {
    id: uuid(),
    type: 'activity',
    title: 'Cena con familia local en Pu Luong',
    description: 'Cena tradicional en el homestay con productos de la zona.',
    tags: ['pu-luong', 'gastronomía', 'cultura'],
    priority: 'must-see',
  },
  {
    id: uuid(),
    type: 'place',
    title: 'Bich Dong',
    description: 'Complejo de pagodas en la montaña cerca de Tam Coc.',
    location: { name: 'Bich Dong', lat: 20.2294, lng: 105.9389 },
    tags: ['ninh-binh', 'templo', 'vistas'],
    priority: 'if-time',
  },
  {
    id: uuid(),
    type: 'activity',
    title: 'Plancton bioluminiscente en Cat Ba',
    description: 'Nadar de noche entre plancton luminiscente en Lan Ha Bay.',
    tags: ['cat-ba', 'lan-ha-bay', 'naturaleza'],
    priority: 'optional',
  },
  {
    id: uuid(),
    type: 'restaurant',
    title: 'Bun bo Hue',
    description: 'Sopa de fideos picante, especialidad de Hue.',
    location: { name: 'Hue', lat: 16.4667, lng: 107.6 },
    tags: ['hue', 'gastronomía', 'picante'],
    priority: 'must-see',
  },
  {
    id: uuid(),
    type: 'place',
    title: 'Marble Mountains',
    description: 'Colinas de mármol con cuevas y pagodas, parada ideal entre Hue y Hoi An.',
    location: { name: 'Marble Mountains', lat: 16.0313, lng: 108.2164 },
    tags: ['da-nang', 'templo', 'naturaleza'],
    priority: 'if-time',
  },
  {
    id: uuid(),
    type: 'activity',
    title: 'Clase de cocina en Hoi An',
    description: 'Aprender a preparar Cao Lau y otros platos locales.',
    location: { name: 'Hoi An', lat: 15.8801, lng: 108.338 },
    tags: ['hoi-an', 'gastronomía', 'experiencia'],
    priority: 'optional',
  },
  {
    id: uuid(),
    type: 'place',
    title: 'Banteay Samre',
    description: 'Templo jemer bien restaurado y menos concurrido.',
    location: { name: 'Banteay Samre', lat: 13.5956, lng: 103.9231 },
    tags: ['siem-reap', 'angkor', 'templos'],
    priority: 'if-time',
  },
  {
    id: uuid(),
    type: 'activity',
    title: 'Kampong Phluk (Tonlé Sap)',
    description: 'Visita a una aldea flotante auténtica en el lago Tonlé Sap.',
    location: { name: 'Kampong Phluk', lat: 13.2019, lng: 104.0114 },
    tags: ['siem-reap', 'cultura', 'naturaleza'],
    priority: 'optional',
  },
])

export const dailyPlans: DailyPlan[] = [
  {
    date: '2026-07-04',
    items: itineraryItems.filter((i) => i.date === '2026-07-04'),
    places: [],
    recommendations: [],
    tips: ['Llegar con tiempo al aeropuerto de Madrid', 'Confirmar asientos con Qatar Airways'],
    culturalNotes: [],
    summary: 'Día de salida desde Madrid con Qatar Airways. Escala en Doha y llegada a Hanói en la mañana del día siguiente.',
  },
  {
    date: '2026-07-05',
    items: itineraryItems.filter((i) => i.date === '2026-07-05'),
    places: places.filter((p) =>
      ['Hanoi Old Quarter', 'Temple of Literature', 'Hoan Kiem Lake', 'Giang Café'].includes(p.name)
    ),
    recommendations: recommendations.filter(
      (r) => r.tags.includes('hanoi') && r.priority === 'must-see'
    ),
    tips: ['Descansar tras el vuelo largo', 'Usar Grab para desplazamientos'],
    culturalNotes: ['El lago Hoan Kiem es sagrado para los vietnamitas.'],
    heroImage: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80',
    summary: 'Llegada a Hanói y primer contacto con Vietnam: paseo por el casco antiguo, el lago Hoan Kiem y el café con huevo en Giang Café.',
  },
  {
    date: '2026-07-06',
    items: itineraryItems.filter((i) => i.date === '2026-07-06'),
    places: places.filter((p) => p.name === 'Pu Luong Nature Reserve'),
    recommendations: recommendations.filter((r) => r.tags.includes('pu-luong')),
    tips: ['El viaje en coche privado suele durar 3,5-4 h', 'Confirmar recogida con el homestay'],
    culturalNotes: ['Las etnias Thai y Muong conservan tradiciones de agricultura en terrazas.'],
    heroImage: 'https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=800&q=80',
    summary: 'Traslado a Pu Luong, una reserva natural de arrozales en terrazas y montañas kársticas con poco turismo.',
  },
  {
    date: '2026-07-07',
    items: itineraryItems.filter((i) => i.date === '2026-07-07'),
    places: places.filter((p) => ['Hieu Waterfall', 'Thai and Muong Villages'].includes(p.name)),
    recommendations: [],
    tips: ['Llevar calzado cómodo para trekking', 'Protector solar y repelente'],
    culturalNotes: [],
    heroImage: 'https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=800&q=80',
    summary: 'Día de trekking por Pu Luong: cascada Hieu, aldeas Thai y Muong y paisajes de arrozales en terrazas.',
  },
  {
    date: '2026-07-08',
    items: itineraryItems.filter((i) => i.date === '2026-07-08'),
    places: places.filter((p) => p.name === 'Tam Coc'),
    recommendations: [],
    tips: ['Viaje de ~3 h hasta Tam Coc'],
    culturalNotes: [],
    heroImage: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?auto=format&fit=crop&w=800&q=80',
    summary: 'Traslado a Ninh Binh y check-in en Tam Coc, punto de partida para explorar el paisaje kárstico de la zona.',
  },
  {
    date: '2026-07-09',
    items: itineraryItems.filter((i) => i.date === '2026-07-09'),
    places: places.filter((p) => ['Trang An', 'Hang Mua', 'Bich Dong'].includes(p.name)),
    recommendations: recommendations.filter((r) => r.title === 'Bich Dong'),
    tips: ['Llegar a Trang An a las 7:00', 'La subida a Hang Mua tiene 500 escalones'],
    culturalNotes: ['Trang An es patrimonio UNESCO por su paisaje kárstico.'],
    heroImage: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?auto=format&fit=crop&w=800&q=80',
    summary: 'Día completo en Ninh Binh: paseo en barca por Trang An, subida a Hang Mua y visita a Bich Dong.',
  },
  {
    date: '2026-07-10',
    items: itineraryItems.filter((i) => i.date === '2026-07-10'),
    places: places.filter((p) => p.name === 'Beo Dock'),
    recommendations: [],
    tips: ['Salida temprana: coche 2 h + ferry 45 min'],
    culturalNotes: [],
    heroImage: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=800&q=80',
    summary: 'Traslado a Cat Ba: coche hasta el puerto, ferry y llegada a la isla para disfrutar de Lan Ha Bay.',
  },
  {
    date: '2026-07-11',
    items: itineraryItems.filter((i) => i.date === '2026-07-11'),
    places: places.filter((p) => ['Viet Hai Floating Village', 'Cat Co Beaches'].includes(p.name)),
    recommendations: recommendations.filter(
      (r) => r.title === 'Plancton bioluminiscente en Cat Ba'
    ),
    tips: ['Excursión en barco desde muelle Beo a las 8:00', 'Mucho menos barcos que Ha Long'],
    culturalNotes: [],
    heroImage: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=800&q=80',
    summary: 'Excursión en barco y kayak por Lan Ha Bay, una alternativa tranquila a la concurrida Ha Long Bay.',
  },
  {
    date: '2026-07-12',
    items: itineraryItems.filter((i) => i.date === '2026-07-12'),
    places: [],
    recommendations: [],
    tips: ['Regreso a Hanói en ferry + coche (~3,5 h)', 'Tarde libre antes del tren nocturno'],
    culturalNotes: [],
    heroImage: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80',
    summary: 'Regreso a Hanói desde Cat Ba y segunda estancia en el Old Quarter antes del tren nocturno a Hue.',
  },
  {
    date: '2026-07-13',
    items: itineraryItems.filter((i) => i.date === '2026-07-13'),
    places: places.filter((p) => ['Ho Chi Minh Mausoleum', 'One Pillar Pagoda'].includes(p.name)),
    recommendations: [],
    tips: ['Tren nocturno a Hue a las 22:00', 'Reservar camarote VIP con antelación'],
    culturalNotes: ['El mausoleo de Ho Chi Minh requiere vestimenta conservadora.'],
    heroImage: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80',
    summary: 'Última mañana en Hanói para visitar el mausoleo de Ho Chi Minh y la Pagoda de un Pilar antes de coger el tren nocturno a Hue.',
  },
  {
    date: '2026-07-14',
    items: itineraryItems.filter((i) => i.date === '2026-07-14'),
    places: places.filter((p) => ['Imperial City', 'Perfume River'].includes(p.name)),
    recommendations: recommendations.filter((r) => r.title === 'Bun bo Hue'),
    tips: ['La estación de tren está céntrica', 'La Ciudad Imperial cierra al atardecer'],
    culturalNotes: ['Hue fue capital imperial de la dinastía Nguyen.'],
    heroImage: 'https://images.unsplash.com/photo-1599708153386-62e6c519a741?auto=format&fit=crop&w=800&q=80',
    summary: 'Llegada a Hue por la mañana y visita a la Ciudad Imperial, antigua capital de la dinastía Nguyen y patrimonio UNESCO.',
  },
  {
    date: '2026-07-15',
    items: itineraryItems.filter((i) => i.date === '2026-07-15'),
    places: places.filter((p) =>
      ['Tomb of Khai Dinh', 'Tomb of Tu Duc', 'Thien Mu Pagoda'].includes(p.name)
    ),
    recommendations: [],
    tips: ['Autobús a Hoi An a las 15:00 (~3 h)', 'Paso de Hai Van con vistas espectaculares'],
    culturalNotes: [],
    heroImage: 'https://images.unsplash.com/photo-1599708153386-62e6c519a741?auto=format&fit=crop&w=800&q=80',
    summary: 'Mañana en Hue visitando las tumbas imperiales y la Pagoda Thien Mu antes de viajar a Hoi An por el Paso de Hai Van.',
  },
  {
    date: '2026-07-16',
    items: itineraryItems.filter((i) => i.date === '2026-07-16'),
    places: places.filter((p) =>
      [
        'Hoi An Ancient Town',
        'Japanese Covered Bridge',
        'An Bang Beach',
        'Tra Que Vegetable Village',
      ].includes(p.name)
    ),
    recommendations: recommendations.filter((r) => r.tags.includes('hoi-an')),
    tips: ['Entrar al casco antiguo a las 8:00 para evitar aglomeraciones'],
    culturalNotes: ['Hoi An fue puerto comercial entre los siglos XV y XIX.'],
    heroImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    summary: 'Día completo en Hoi An: casco antiguo UNESCO, puente japonés, playa de An Bang y taller de linternas de seda.',
  },
  {
    date: '2026-07-17',
    items: itineraryItems.filter((i) => i.date === '2026-07-17'),
    places: places.filter((p) => p.name === 'Marble Mountains'),
    recommendations: recommendations.filter((r) => r.title === 'Marble Mountains'),
    tips: ['Taxi a Da Nang ~45 min', 'Vuelo DAD → SAI pendiente de reservar'],
    culturalNotes: [],
    heroImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    summary: 'Mañana libre en Hoi An, traslado a Da Nang para volar a Siem Reap y primer contacto con Camboya.',
  },
  {
    date: '2026-07-18',
    items: itineraryItems.filter((i) => i.date === '2026-07-18'),
    places: places.filter((p) => ['Srah Srang', 'Bayon', 'Ta Prohm'].includes(p.name)),
    recommendations: [],
    tips: ['Pase Angkor 3 días: 62 USD/pers', 'Tuk-tuk todo el día ~15-20 USD'],
    culturalNotes: ['Angkor Thom fue la última capital del Imperio Jemer.'],
    heroImage: 'https://images.unsplash.com/photo-1600520611035-8a297f05bf7e?auto=format&fit=crop&w=800&q=80',
    summary: 'Primer día en el complejo de Angkor: amanecer en Srah Srang, circuito grande con Bayon y Ta Prohm.',
  },
  {
    date: '2026-07-19',
    items: itineraryItems.filter((i) => i.date === '2026-07-19'),
    places: places.filter((p) => ['Banteay Srei', 'Kbal Spean'].includes(p.name)),
    recommendations: recommendations.filter((r) => r.title === 'Banteay Samre'),
    tips: ['Bus nocturno a Phnom Penh pendiente de reservar', 'Llevar efectivo para pagos'],
    culturalNotes: [],
    heroImage: 'https://images.unsplash.com/photo-1600520611035-8a297f05bf7e?auto=format&fit=crop&w=800&q=80',
    summary: 'Segundo día en Angkor: Banteay Srei, Kbal Spean y preparativos para el bus nocturno a Phnom Penh.',
  },
  {
    date: '2026-07-20',
    items: itineraryItems.filter((i) => i.date === '2026-07-20'),
    places: [],
    recommendations: [],
    tips: ['Vuelo temprano PNH 08:35', 'Llegada a Madrid el mismo día'],
    culturalNotes: [],
    summary: 'Día de vuelta: salida temprana desde Phnom Penh con Etihad y llegada a Madrid tras escala en Abu Dhabi.',
  },
]

export function getSeedData() {
  return {
    travelers,
    documents,
    itineraryItems,
    places,
    dailyPlans,
    recommendations,
    countryInfo,
    packingItems,
    preTravelSections,
  }
}
